# tasks file for duplicity
---
- name: install | native | dependencies
  apt:
    name: "{{ duplicity_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - duplicity-install-native-dependencies
