# tasks file
---
- name: install | ppa | dependencies (pre)
  ansible.builtin.apt:
    name: "{{ duplicity_ppa_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - duplicity-install-ppa-dependencies

- name: install | ppa | add repository and its signing key
  ansible.builtin.apt_repository:
    repo: "{{ duplicity_ppa_stable }}"
    update_cache: true
    mode: 0644
  tags:
    - duplicity-install-ppa-add-repository

- name: install | ppa | dependencies
  ansible.builtin.apt:
    name: "{{ duplicity_ppa_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - duplicity-install-ppa-dependencies
