# tasks file
---
- name: install | pip | remove (distro version)
  apt:
    name: "{{ duplicity_package_name }}"
    state: absent
    purge: true
  tags:
    duplicity-install-pip-remove
    duplicity-install-pip-remove-distro-version

- name: install | pip | dependencies | pre
  apt:
    name: "{{ duplicity_pip_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    duplicity-install-pip-dependencies-pre

- name: install | pip | dependencies | pre
  pip:
    name: "{{ duplicity_pip_dependencies_pre_python }}"
    executable: "{{ duplicity_pip_pip_executable }}"
  tags:
    duplicity-install-pip-dependencies-pre

- name: install | pip | dependencies
  pip:
    name: "{{ duplicity_pip_dependencies_python }}"
    executable: "{{ duplicity_pip_pip_executable }}"
  tags:
    - duplicity-install-pip-dependencies

- name: install | pip | fix shebang
  replace:
    path: "{{ duplicity_pip_duplicity_path }}"
    regexp: '^\#\!\/usr\/bin\/env\ python3$'
    replace: '#!/usr/bin/env python2'
  when: ansible_distribution_major_version is version('20', '<')
  tags:
    - duplicity-install-pip-fix-shebang
