# tasks file
---
- ansible.builtin.include: install-native.yml
  when: duplicity_install_method == 'native'
  tags:
    - configuration
    - duplicity
    - duplicity-install-native

- ansible.builtin.include: install-ppa.yml
  when: duplicity_install_method == 'ppa'
  tags:
    - configuration
    - duplicity
    - duplicity-install-ppa

- ansible.builtin.include: install-pip.yml
  when: duplicity_install_method == 'pip'
  tags:
    - configuration
    - duplicity
    - duplicity-install-pip

- name: install additional
  ansible.builtin.apt:
    name: "{{ duplicity_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - duplicity
    - duplicity-install
    - duplicity-install-additional

- name: verify
  ansible.builtin.command: >
    duplicity --version
  changed_when: false
  tags:
    - configuration
    - duplicity
    - duplicity-install
    - duplicity-install-verify
