# tasks file for duplicity
---
- name: add repository from PPA and install its signing key
  apt_repository:
    repo: 'ppa:duplicity-team/ppa'
    update_cache: true
  tags:
    - configuration
    - duplicity
    - duplicity-add-repository

- name: install dependencies
  apt:
    name: "{{ duplicity_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - duplicity
    - duplicity-dependencies

- name: install
  apt:
    name: "{{ duplicity_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - duplicity
    - duplicity-install
