# tasks file for duplicity
---
- include: install-native.yml
  when: duplicity_install_method == 'native'
  tags:
    - configuration
    - duplicity
    - duplicity-install-native

- include: install-ppa.yml
  when: duplicity_install_method == 'ppa'
  tags:
    - configuration
    - duplicity
    - duplicity-install-ppa

- include: install-pip.yml
  when: duplicity_install_method == 'pip'
  tags:
    - configuration
    - duplicity
    - duplicity-install-pip

- name: install additional
  apt:
    name: "{{ duplicity_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - duplicity
    - duplicity-install
    - duplicity-install-additional
